### ISSUE TITLE
Fix for Running Receiver and Sender at the same time on a Single Server

### ISSUE THREAD

**Issue by Michael-Reidy** [spring-projects/spring-amqp-samples#12]
In order to avoid port clashes between sender and receivers in the RabbitMQ tutorials project it would be better to have the receiver start on a different port than the sender.

I fixed this on my copy of the application by doing this.

````java
@Profile("receiver")
  private static class ReceiverConfig {

    @Bean
    public EmbeddedServletContainerCustomizer containerCustomizer() {
      return (container -> {
        container.setPort(8012);
      });
    }

    @Bean
    public Tut5Receiver receiver() {
      return new Tut5Receiver();
    }
````

**Comment by garyrussell** [comment]
Thanks for pointing this out; you can simply add...

    server:
      port: 0

To `application.yml` to use a random port for each.

We should probably turn off Tomcat altogether though.

**Comment by Michael-Reidy** [comment]
That's even better! Cheers!

**Comment by artembilan** [comment]
@Michael-Reidy , how about to contribute your experience back to the Samples project https://github.com/spring-projects/spring-amqp?

Thank you for pointing that out anyway!
