### ISSUE TITLE
Add example for delayed message 

### ISSUE THREAD

**Issue by rkazanova** [spring-projects/spring-amqp-samples#14]

**Comment by artembilan** [comment]
Why do you think that the Reference Manual [chapter](http://docs.spring.io/spring-amqp/docs/1.6.0.RELEASE/reference/html/_reference.html#delayed-message-exchange) isn't enough?

What do you have in mind to be represented as a sample here?

The [Rabbit MQ Delayed Message Plugin](https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/) functionality looks obvious as well.

So, please, share some scenario which would fit as a simple sample for newbies.

**Comment by rkazanova** [comment]
Sorry. I found Reference Manual chapter i after creating this issue.
