### ISSUE TITLE
Wrong documentation for delayed message

### ISSUE THREAD

**Issue by fjmpaez911** [spring-projects/spring-amqp-samples#21]
In the [chapter](http://docs.spring.io/spring-amqp/docs/1.6.0.RELEASE/reference/html/_reference.html#delayed-message-exchange) of Reference Manual said:

`properties.setXDelay(15000);`

when this method doesn't exists.

The correct method is **(setDelay):**

/**
     * Set the x-delay header.
     * @param delay the delay.
     * @since 1.6
     */
    public void setDelay(Integer delay) {
    	if (delay == null || delay < 0) {
    		this.headers.remove(X_DELAY);
    	}
    	else {
    		this.headers.put(X_DELAY, delay);
    	}
    }

**Comment by artembilan** [comment]
Please, this a a bug into appropriate JIRA: https://jira.spring.io/browse/AMQP

This project is exactly for `samples`. But Reference Manual you are pointing is from core Spring AMPQ project: https://github.com/spring-projects/spring-amqp

Thank you for catching that out any way!
