### ISSUE TITLE
Spring Rabbit Json pom.xml points to non existing repo? 

### ISSUE THREAD

**Issue by chhex** [spring-projects/spring-amqp-samples#23]
For  <url>http://repo.spring.io/repo</url>
i get 

{
  "errors" : [ {
    "status" : 404,
    "message" : "Not Found"
  } ]
}

see also 
`<repositories>
          <repository>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
                        <id>repository.springframework.maven.all</id>
                        <name>Spring Framework Repository Including Staging</name>
                        <url>http://repo.spring.io/repo</url>
                </repository>
	</repositories>`
> 

in the pom.xml of spring-rabbit-json

**Comment by garyrussell** [comment]
Yes; we just noticed that repo no longer exists after an artifactory upgrade.

Please use this instead...

```xml
<repositories>
	<repository>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<id>repository.springframework.maven.all</id>
			<name>Spring Framework Repository Including Snapshots</name>
			<url>http://repo.spring.io/libs-snapshot</url>
	</repository>
</repositories>
```

**Comment by chhex** [comment]
Great thanks!
