### ISSUE TITLE
log4j module have error when run

### ISSUE THREAD

**Issue by genericyzh** [spring-projects/spring-amqp-samples#26]
`java.lang.NoSuchMethodError: org.springframework.core.MethodParameter.nestedIfOptional()Lorg/springframework/core/MethodParameter;`

maybe spring version too low(4.2.9);
this method is suported by 4.3

**Comment by garyrussell** [comment]
Please see the [README.md](https://github.com/spring-projects/spring-integration-samples#note).

>__NOTE__

>This (master) branch requires Spring Integration 5.0 or above. For samples running against earlier versions of Spring Integration, use the SI4.3.x and other branches.

**Comment by genericyzh** [comment]
yeah,i'm using master branch,so why the pom.xml of log4j module isn't use 5.0 version?
<properties>
	<maven.test.failure.ignore>true</maven.test.failure.ignore>
	<spring.framework.version>4.2.9.RELEASE</spring.framework.version>
	<spring.amqp.version>1.7.2.RELEASE</spring.amqp.version>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>

**Comment by garyrussell** [comment]
Sorry - my note is for the Spring Integration Samples (wrong repo; sorry).

**Comment by garyrussell** [comment]
I am not familiar with that sample; where are you seeing that error?

**Comment by garyrussell** [comment]
Fixed [on master](https://github.com/spring-projects/spring-amqp-samples/commit/efc5878b9c7e698c387454add6efa8dace5e52af); thanks.

**Comment by genericyzh** [comment]
when i run log4j module whth tomcat 7, tomcat display this error.
you can have a try~
