### ISSUE TITLE
build stock has error

### ISSUE THREAD

**Issue by datctbk** [spring-projects/spring-amqp-samples#33]
Hi!
Thank in advance for any help.
I use apache maven 3.3.3 to build stock.
Here is the errors:
[ERROR] Failed to execute goal on project spring-rabbit-stocks: Could not resolve dependencies for project org.springframework.samples.spring:spring-rabbit-stocks:war:2.1.0.RC1: The following artifacts could not be resolved: org.springframework.amqp:spring-amqp:jar:2.1.0.RC1, org.springframework.amqp:spring-rabbit:jar:2.1.0.RC1: Failure to find org.springframework.amqp:spring-amqp:jar:2.1.0.RC1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project spring-rabbit-stocks: Could not resolve dependencies for project org.springframework.samples.spring:spring-rabbit-stocks:war:2.1.0.RC1: The following artifacts could not be resolved: org.springframework.amqp:spring-amqp:jar:2.1.0.RC1, org.springframework.amqp:spring-rabbit:jar:2.1.0.RC1: Failure to find org.springframework.amqp:spring-amqp:jar:2.1.0.RC1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by garyrussell** [comment]
The release candidate (RC1) is in repo.spring.io/milestone.

I have updated the samples to use 2.1.0.RELEASE.
