### ISSUE TITLE
RabbitMQ - Socket Exception

### ISSUE THREAD

**Issue by Nandha13** [spring-projects/spring-amqp-samples#34]
Getting this exception when our code in our endpoints trying to communicate with RMQ . We are using cachingConnectionFactory and TopicExchange.

``error=org.springframework.amqp.AmqpIOException: java.net.SocketException: Connection timed out (Write failed) at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:63) at org.springframework.amqp.rabbit.connection.RabbitAccessor.convertRabbitAccessException(RabbitAccessor.java:110) at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:968) at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:945) at org.springframework.amqp.rabbit.core.RabbitTemplate.send(RabbitTemplate.java:470) at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:535) at org.springframework.amqp.rabbit.core.RabbitTemplate.convertAndSend(RabbitTemplate.java:522)
``

**Comment by garyrussell** [comment]
It means there was a timeout on the write. You should ask such questions on the rabbitmq-users google group.

Feel free to post a link here.

**Comment by garyrussell** [comment]
It means there was a timeout on the write. Look in the server log for any clues. You should ask such questions on the rabbitmq-users google group.

Feel free to post a link here.
