### ISSUE TITLE
spring-amqp with mqtt

### ISSUE THREAD

**Issue by jamesWjc** [spring-projects/spring-amqp-samples#8]
spring-amqp publish message,mqtt subscribe.
I have successfully implemented publish/subscribe.
for example publish :

````java
CachingConnectionFactory cf = new CachingConnectionFactory();
RabbitAdmin admin = new RabbitAdmin(cf);

MessageProperties props = MessagePropertiesBuilder.newInstance()
                .setContentType(MessageProperties.CONTENT_TYPE_TEXT_PLAIN)
                .build();
Message message = MessageBuilder.withBody("ok!".getBytes("UTF-8"))
                .andProperties(props)
                .build();
RabbitTemplate template = admin.getRabbitTemplate();
template.send("amq.topic", "test.*", message);
````

What do I need to add code,confirm mqtt successfully received a message?
Besides,listen queue remove/add need code

**Comment by artembilan** [comment]
Hi @jamesWjc !

First of all thank you for attention to this stuff.

From other side it isn't clear what you ask.
Please, rephrase your issue.

And one more point: Spring AMQP doesn't provide any API to get deal with MQTT.
You should refer to the Spring Integration MQTT adapters on the matter: 
http://docs.spring.io/spring-integration/docs/latest-ga/reference/html/mqtt.html

And here is a test-case from RabbitMQ team to test MQTT plugin:
http://hg.rabbitmq.com/rabbitmq-mqtt/file/default/test/src/com/rabbitmq/mqtt/test/MqttTest.java

Cheers,
Artem

**Comment by jamesWjc** [comment]
Thanks artembilan,
I want to listen rabbitmq's queue,when it remove or add.
And listening message consumed in queue.
spring-amqp can do.

**Comment by artembilan** [comment]
Sorry, it is a lack of information anyway...
Please, don't hesitate to express your thoughts. 
Otherwise we aren't able to help you.
